{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyN4JD/su6rWNcdOUSuKDn9Q"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["# Hatalar ve İstisnalar (Error and Exceptions)\n","\n","Python programlamada \"hata (error)\" ve \"istisna (exception)\" terimleri arasındaki fark, genellikle hataların ne zaman ve nasıl ortaya çıktığına bağlı olarak belirlenir. İki terim aşağıdaki gibi açıklanabilir:\n","\n","### Error\n","\"Error\" terimi, genellikle programın çalışmasını tamamen durdurabilecek ciddi problemleri ifade etmek için kullanılır. Bunlar arasında en yaygın olanı \"syntax errors\" (sözdizimi hataları) gibi, program çalıştırılmadan önce tespit edilen ve çoğunlukla programcının kodu derleyici veya yorumlayıcı tarafından reddedilene kadar farkına varmadığı hatalardır. Bu tür hatalar, genellikle yazım hataları, yanlış girintileme veya dilin söz dizimsel kurallarına uyulmamasından kaynaklanır.\n","\n","\n","### Exception\n","\"Exception\" ise, sözdizimi doğru olmasına rağmen çalışma zamanında (runtime) karşılaşılan ve işlenmediği takdirde programın anormal şekilde sonlanmasına neden olabilecek hatalardır. Bunlar, programın akışı sırasında ortaya çıkabilir ve uygun şekilde ele alınırlarsa, programın kapanmasını önlemek ve hata ile uygun bir şekilde başa çıkmak mümkün olabilir. Python’da `ZeroDivisionError`, `NameError`, `TypeError` gibi istisnalar bu kategoriye girer."],"metadata":{"id":"jH8FjK2ZK99_"}},{"cell_type":"markdown","source":["### 1. Hata Türleri\n","\n","Python'da genellikle iki ana hata türü ile karşılaşılır: Sözdizimi hataları (syntax errors) ve istisnalar (exceptions).\n","\n","#### Sözdizimi Hataları\n","Sözdizimi hataları, Python yorumlayıcısının programı çalıştırmadan önce kodda bulduğu hatalardır. En yaygın örnekler:\n","- `SyntaxError:`Eksik parantez, tırnak işareti ya da virgül\n","- `SyntaxError:` Atama işleminde `=` yerine `==` kullanılması\n","- `IndentationError:`Yanlış girintileme"],"metadata":{"id":"2nwdxoOgKTXA"}},{"cell_type":"code","source":["print(\"Merhaba"],"metadata":{"id":"oxzubdgrK2UK"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["for i in range\n","  print(i)"],"metadata":{"id":"CgKrEZcKMEhQ"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["if x = 10:\n","    print(x)"],"metadata":{"id":"PoW8NelsKX1a"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["for i in range:\n","print(i)"],"metadata":{"id":"Yi07Z9GLMLLo"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# kullanıcıdan veril girilmesi istendiğinde Ctrl+D kombinasyonuna basılırsa\n","# EOFError hatası verir\n","data = input(\"Lütfen bir şeyler yazın: \")"],"metadata":{"id":"4HmUZfTJv30Q"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["#### İstisnalar\n","İstisnalar, sözdizimi doğru olsa bile çalışma zamanında karşılaşılan hatalardır. Örnekler:\n","\n","- `ZeroDivisionError`: Sıfıra bölme hatası\n","\n","- `NameError`: Tanımlanmamış bir değişken kullanıldığında\n","\n","- `TypeError`: Veri türleri arası uyumsuz işlemler\n","\n","- `ValueError:`  Bir fonksiyonun, kendisi için uygun olmayan bir değerle çağrılması sonucunda meydana gelir.\n","\n","- `IndexError:` Bir dizin (list, tuple, string vb.) içinde geçersiz bir indeksle eleman erişimi yapmaya çalıştığınızda ortaya çıkar.\n","\n","- `EOFError:` Karşılaşabileceğiniz en yaygın sebebi, `input()` fonksiyonunda girdi akışının beklenmedik bir şekilde sonlandırılması, `Ctrl+D` (Linux veya MacOS'ta) veya `Ctrl+Z` ve `Enter` (Windows'ta) tuş kombinasyonlarına basılması, durumlarında ortaya çıkar."],"metadata":{"id":"fwTlPzvkNEO3"}},{"cell_type":"code","source":["2 / 0  # Sıfıra bölme hatası"],"metadata":{"id":"T74pvUniNJxA"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["print(a)  # 'a' değişkeni tanımlanmamış"],"metadata":{"id":"x6gpsfguNSr3"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["sayi = 5\n","metin = \"3\"\n","sonuc = sayi + metin  # int ile str toplanamaz TypeError\n","sayı > metin  # int ile str karşılaştırılamaz TypeError"],"metadata":{"id":"JF38LQycNVbP"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["int(\"abc123\") # ValueError"],"metadata":{"id":"RSOfzjK_PFRZ"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# IndexError\n","liste = [1, 2, 3]\n","liste.pop(4)"],"metadata":{"id":"XuHB_FxRPtRJ"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["**NOT:** Python programlamada karşılaşabileceğiniz yaygın hata ve istisna türlerini tanımanız önemlidir, çünkü bu bilgi hata ayıklama sürecinde size büyük yardımcı olacaktır. Ancak, Python'daki tüm hata ve istisna türlerini ezberlemeniz beklenmez. Çünkü bu, zaman alıcı ve pratik olmayan bir yaklaşım olurdu. Bunun yerine, karşılaştığınız spesifik hata ve istisnalar hakkında daha fazla bilgi edinmek ihtiyacı duyduğunuzda Python'un resmi belgelerini veya online web sitelerini ziyaret etmenizi öneririm. Python'un kapsamlı belgeleri, her bir hata ve istisna türü için detaylı açıklamalar sunar ve çeşitli örneklerle destekler.\n","\n","[Python Resmi Belgesi - Hatalar ve İstisnalar için Tıklayınız](https://docs.python.org/3/library/exceptions.html)"],"metadata":{"id":"Y7-9F84KQ6qA"}},{"cell_type":"markdown","source":["### 2. İstisna Yakalama\n","\n","Python'da `try` ve `except` blokları kullanılarak istisnalar yakalanabilir. Bu yapı hataları ele almanın ve programın çökmesini önlemenin bir yoludur. Yapısı aşağıdaki gibidir:\n","\n","\n","```python\n","try:\n","    # Hata çıkarabilecek kodlar buraya yazılır.\n","    # Eğer hata çıkarsa, uygun olan except bloğuna geçilir.\n","    # Hata oluşursa, try bloğunun geri kalan kısmı çalışmaz. Yani karşılaştığı ilk hatada try bloğundan çıkar.\n","except HataTürü1:\n","    # HataTürü1 meydana geldiğinde burası çalışır.\n","except HataTürü2:\n","    # HataTürü2 meydana geldiğinde burası çalışır.\n","```\n","Herhangi bir except'in yanına herhangi bir hata türü yazmadığımız durumda tüm hata türleri için o except bloğu çalışır.\n","\n","**Örnek:**"],"metadata":{"id":"kmGyIR8oSMzu"}},{"cell_type":"code","source":["try:\n","    # Hata verebilecek kod\n","    print(\"try'in içinde ilk satır\")\n","    sonuc = 2 / 0 # hata veren\n","    print(\"try'in içinde son satır\")\n","except: # except'in yanına hata türü/türleri yazılır\n","    # Hata durumunda yapılacak işlem\n","    print(\"HATA VAR\")\n","\n","print(\"try-except bloklarının dışı\")"],"metadata":{"id":"6Jk6nD29Tah_"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["try:\n","    # Hata verebilecek kod\n","    print(\"try'in içinde ilk satır\")\n","    a = int(5)\n","    print(\"try'in içinde son satıra geldik hiç hata yok\")\n","except: # except'in yanına hata türü/türleri yazılır\n","    # Hata durumunda yapılacak işlem\n","    print(\"HATA VAR\")\n","\n","print(\"try-except bloklarının dışı\")"],"metadata":{"id":"GeN2OMJKaHDo"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["try:\n","    sonuc = int('5a')\n","    sonuc = 2 / 1\n","except ZeroDivisionError: # sadece sıfıra bölme hatasında çalışır\n","    # Hata durumunda yapılacak işlem\n","    print(\"Hata: Bir sayıyı sıfıra bölemessiniz.\")"],"metadata":{"id":"VTPXjXm-beqJ"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["### 3. Çoklu İstisnalar\n","\n","Bir `try` bloğunda birden fazla hata türü yakalanabilir. Bu, farklı hatalara farklı tepkiler vermek için kullanılır.\n","\n","**Örnek:** Kullanıcıdan iki sayı alıp bölme işlemi yapalım."],"metadata":{"id":"-Qow910TThp3"}},{"cell_type":"code","source":["sayi1 = int(input(\"Birinci sayıyı giriniz: \"))"],"metadata":{"id":"9_jHCbB8bAoQ"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["sonuc = 2 / 0"],"metadata":{"id":"S-QbsqTBbDYg"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["try:\n","    # Hata verebilecek kod bloğu\n","    sayi1 = int(input(\"Birinci sayıyı giriniz: \"))\n","    sayi2 = int(input(\"İkinci sayıyı giriniz: \"))\n","    sonuc = sayi1 / sayi2\n","    print(\"Sonuç: {}\".format(sonuc))\n","    print(\"Herhangi bir hata yok.\")\n","except ValueError:\n","    print(\"Hata: Lütfen sadece sayısal değerler giriniz.\")\n","except ZeroDivisionError:\n","    print(\"Hata: Bir sayıyı sıfıra bölemessiniz.\")"],"metadata":{"id":"u4oQNz8hTh8n"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["try:\n","    # Hata verebilecek kod bloğu\n","    sayi1 = int(input(\"Birinci sayıyı giriniz: \"))\n","    sayi2 = int(input(\"İkinci sayıyı giriniz: \"))\n","    sonuc = sayi1 / sayi2\n","    print(\"Sonuç: {}\".format(sonuc))\n","    print(\"Herhangi bir hata yok.\")\n","except (ValueError, ZeroDivisionError):\n","    print(\"Bir hata oluştu\")"],"metadata":{"id":"VuExaepffHgg"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["**NOT:** Python'da `except` ifadesi ile hata yakalama yaparken `as e` kullanımı, yakalanan hata nesnesini bir değişkene atayarak, hata hakkında daha fazla bilgi edinmek ve bu bilgiyi işlemek için kullanılır. Bu, hata yönetimi sürecinde oldukça yararlıdır çünkü hata mesajını, hata türünü ve hata ile ilgili diğer detayları elde edebilir ve kullanabilirsiniz."],"metadata":{"id":"1zwDZ-SuwWhP"}},{"cell_type":"code","source":["try:\n","    sayi1 = int(input(\"Birinci sayıyı giriniz: \"))\n","    sayi2 = int(input(\"İkinci sayıyı giriniz: \"))\n","    sonuc = sayi1 / sayi2\n","    print(\"Sonuç: {}\".format(sonuc))\n","except (ValueError, ZeroDivisionError) as e:\n","    print(f\"Hata oluştu: {e}\")"],"metadata":{"id":"cqJ4apEuwaYP"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["- Hata yakalandığında, `except` bloğu çalışır ve hata mesajı `e` nesnesi içinde saklanır. Bu mesaj, hatanın ne olduğunu açıklar.\n","\n","- `as e` kullanımı, programcılara hata hakkında doğrudan bilgi sağlar, böylece uygun hata mesajlarını kullanıcıya sunabilir veya hata günlüğüne yazdırabilirsiniz. Bu, özellikle birden fazla hata türünü aynı `except` bloğunda yakaladığınızda, hangi hatanın gerçekleştiğini belirlemenizi kolaylaştırır."],"metadata":{"id":"15yzRzLswalP"}},{"cell_type":"markdown","source":["### 4. `else` ve `finally` Blokları\n","\n","`else` bloğu, hata oluşmadığı zaman çalışır. `finally` bloğu ise hata olsun ya da olmasın her durumda çalışır.\n","\n","**Genişletilmiş try-except-else-finally Yapısı:**\n","\n","```python\n","try:\n","    # Hata çıkarabilecek kodlar buraya yazılır.\n","    # Eğer hata çıkarsa, uygun olan except bloğuna geçilir.\n","    # Hata oluşursa, try bloğunun geri kalan kısmı çalışmaz. Yani karşılaştığı ilk hatada try bloğundan çıkar.\n","except HataTürü1:\n","    # HataTürü1 meydana geldiğinde burası çalışır.\n","except HataTürü2:\n","    # HataTürü2 meydana geldiğinde burası çalışır.\n","except (HataTürü1,HataTürü2):\n","    # HataTürü1 veya HataTürü2 meydana geldiğinde burası çalışır.\n","except (HataTürü1,HataTürü2) as e:\n","    # HataTürü1 veya HataTürü2 meydana geldiğinde burası çalışır. ve ilgili hata mesajı `e` nesnesi içinde saklanır.   \n","except:\n","    # Hata türü belirtilmediğinde tüm diğer hatalar bu blokta işlenir.\n","else:\n","    # Eğer try bloğunda hiç hata meydana gelmezse else bloğu çalışır.\n","finally:\n","    # Bu blok, hata olsun ya da olmasın her durumda çalışır.\n","```\n","\n","**`else` Bloğu:**, `try` bloğundaki kodların hata üretmeden başarıyla çalışması durumunda çalışan bir bloktur. Genellikle, hata potansiyeli taşımayan ama `try` bloğundaki işlemlerden sonra çalıştırılması gereken kodları içerir. Örneğin, bir dosya okuma işlemi başarıyla tamamlandıktan sonra dosya içeriğini işlemek için kullanılabilir.\n","\n","**`finally` Bloğu:**, `try-except` yapısının en sonunda yer alır ve `try` bloğunda ne olursa olsun çalıştırılması gereken kodları içerir. Bu blok genellikle kaynakların temizlenmesi, dosyaların kapatılması veya kritik son işlemlerin yapılması için kullanılır.\n","\n","\n","**Örnek:**"],"metadata":{"id":"Qe1jFyMrTlKX"}},{"cell_type":"code","source":["try:\n","    sonuc = 10 / 5\n","except ZeroDivisionError:\n","    print(\"Bir sayıyı sıfıra bölemezsiniz.\")\n","else:\n","    print(\"İşlem başarılı.\")\n","finally:\n","    print(\"Bu blok her durumda çalışır.\")"],"metadata":{"id":"wna82DsoTlQC"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["while True:\n","    try:\n","        # Hata verebilecek kod bloğu\n","        sayi1 = int(input(\"Birinci sayıyı giriniz: \"))\n","        sayi2 = int(input(\"İkinci sayıyı giriniz: \"))\n","        sonuc = sayi1 / sayi2\n","        print(\"Sonuç: {}\".format(sonuc))\n","    except (ValueError, ZeroDivisionError) as e:\n","        print(f\"\\nHata oluştu: {e}\")\n","    else:\n","        print(\"\\nHerhangi bir hata yok. İşlem başarılı.\")\n","        break # herhangi bir hata yoksa while kır\n","    finally:\n","        print(\"finally bloğu her durumda çalışır.\\n\")"],"metadata":{"id":"g2WQMcTKyqFJ"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["#### Hata Fırlatma (İstisna Oluşturma) (Raise an exception)\n","Bazen, fonksiyonlarımızı yanlış kullanımlara karşı korumak için kendi hatalarımızı fırlatmamız (istisnalar oluşturmamız) gerekebilir. Python'da bu, `raise` anahtar kelimesi ile yapılır.\n","\n","```python\n","raise HataTürü(\"Hata mesajı\")\n","```\n","\n","Konsol çıktısı Python'un standart hata gösterimi şeklindedir. `try`- `except` blokları ile kendi oluşturduğumuz `raise` hata fırlatmasını istediğimiz şekilde yönetebiliriz.\n","\n","**Örnek:**"],"metadata":{"id":"FGK5jyjdSLsH"}},{"cell_type":"code","source":["# kendi fonksiyonumuza bir hata fırlatma tanımlayalım\n","def yas_kontrol(yas):\n","    if yas < 0:\n","        raise ValueError(\"Yaş negatif olamaz!\")\n","    elif yas > 120:\n","        raise ValueError(\"Yaş bu kadar büyük olamaz!\")\n","    return f\"Girilen yaş: {yas}\""],"metadata":{"id":"5z3Hmq7-1ox5"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["yas_kontrol(-5)"],"metadata":{"id":"5PtKZBZD1t-S"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["yas_kontrol(124)"],"metadata":{"id":"-EPIwJTP3bqJ"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["try:\n","    sonuc = yas_kontrol(-5)\n","    sonuc2 = yas_kontrol(125)\n","except ValueError as e:\n","    print(\"Hata:\", e)"],"metadata":{"id":"BkBopkg51r8o"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["### **`isinstance()` fonksiyonu**\n","\n","Python'da bir değişkenin belirli bir veri türüne veya sınıfa (class) ait olup olmadığını kontrol etmek için kullanılır. Bu fonksiyon, ilk parametre olarak bir nesne (object) ve ikinci parametre olarak bir veri türü veya bir sınıf alır. Eğer nesne, belirtilen türden ise `True`, değilse `False` döner.\n","\n","***Temel Veri Türlerini Kontrol Etme***"],"metadata":{"id":"uuTyH5IQ2UCX"}},{"cell_type":"code","source":["num = 3.14\n","print(isinstance(num, float))  # True çünkü num bir float'tır"],"metadata":{"id":"Ywv0IG5s2UMQ"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["print(isinstance(num, int))  # False çünkü num bir float'tır"],"metadata":{"id":"CbmXX7AKQ2DC"},"execution_count":null,"outputs":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ApsVdFApi5g8"},"outputs":[],"source":["text = \"Merhaba\"\n","print(isinstance(text, str))   # True çünkü text bir string'tir"]},{"cell_type":"code","source":["numbers = [1, 2, 3]\n","print(isinstance(numbers, list))  # True çünkü numbers bir list'tir"],"metadata":{"id":"cgNQ5KDf2qpP"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["print(isinstance(numbers, dict))  # False çünkü numbers bir dictionary değil"],"metadata":{"id":"Z8WtKN8H2sfv"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["def veri_kontrolu(data):\n","    try:\n","        if isinstance(data, list):\n","            print(\"Veri listesi işleniyor...\")\n","            veri_isleme = [x * 2 for x in data]\n","            print(\"İşlenmiş veri:\", veri_isleme)\n","        else:\n","            raise TypeError(\"Veri bir liste tipinde olmalıdır.\")\n","    except TypeError as e:\n","        print(\"Hata:\", e)\n","\n","# Doğru veri tipiyle çağrıldığında\n","veri_kontrolu([1, 2, 3, 4])\n","\n","# Yanlış veri tipiyle çağrıldığında\n","veri_kontrolu(\"Bu bir string\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"W2lI0znVn3dB","executionInfo":{"status":"ok","timestamp":1714642027302,"user_tz":-180,"elapsed":266,"user":{"displayName":"Fesih KESKİN","userId":"17449053008709092040"}},"outputId":"e5273275-6d42-473a-dbf5-d62f0c6bfb7c"},"execution_count":2,"outputs":[{"output_type":"stream","name":"stdout","text":["Veri listesi işleniyor...\n","İşlenmiş veri: [2, 4, 6, 8]\n","Hata: Veri bir liste tipinde olmalıdır.\n"]}]},{"cell_type":"markdown","source":["---\n","**Python'da dosya işlemleri sırasında hata yönetimi**\n","\n","Özellikle dosya erişimi ve dosya okuma/yazma işlemleri sırasında karşılaşılabilecek sorunları ele almak için son derece önemlidir. Bu işlemler sırasında en sık karşılaşılan hatalar `FileNotFoundError`, `IOError`, `PermissionError` ve `EOFError` gibi hatalardır. Python'da bu tür hataları yönetmek için `try`, `except`, `else`, ve `finally` blokları kullanılır. İşte bu konseptleri açıklığa kavuşturacak bir ders notu ve örnek kod:\n","\n","\n","#### Temel Hata Türleri:\n","1. **FileNotFoundError**: İstenen dosya bulunamadığında ortaya çıkar.\n","2. **PermissionError**: Dosya üzerinde okuma/yazma gibi işlemler için gerekli izinlerin olmaması durumunda bu hata ile karşılaşılır.\n","3. **IOError**: Dosya okuma/yazma işlemleri sırasında I/O hatası meydana geldiğinde bu hata alınır.\n","4. **EOFError**: Dosya sonuna beklenenden erken ulaşıldığında bu hata oluşur.\n","\n","#### Hata Yönetimi Blokları:\n","- **try Bloğu**: Hata oluşabilecek kod bu blok içerisine yazılır.\n","- **except Bloğu**: Hata meydana geldiğinde çalışacak olan kod bu blok içerisine yazılır.\n","- **else Bloğu**: Hata oluşmadığında çalışacak kod buraya yazılır.\n","- **finally Bloğu**: Hata olsun ya da olmasın çalıştırılacak olan kod bu bloğa yazılır. Örneğin, bir dosyayı kapatmak gibi işlemler bu blok içerisinde yer alabilir."],"metadata":{"id":"u9IBpMigaASx"}},{"cell_type":"code","source":["file = open(\"yeni_dosya.txt\",\"r\",encoding = \"utf-8\")\n","print(file.read())"],"metadata":{"id":"7HYiF4inalKQ"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["file = open(\"yeni_dosya.txt\",\"w\",encoding = \"utf-8\")\n","file.write('Merhaba')\n","\n","try:\n","  dosya_adi = \"yeni_dosya2.txt\"\n","  file = open(dosya_adi,\"r\",encoding = \"utf-8\")\n","  print(file.read())\n","except FileNotFoundError:\n","  print(f\"Dizinde {dosya_adi} isimli dosya bulunmamaktadır.\")\n","finally:\n","  file.close()"],"metadata":{"id":"EFpXVG4kakCQ"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["try:\n","    # Dosya açma işlemi\n","    with open('yeni_dosya.txt', 'r') as dosya:\n","        icerik = dosya.read()\n","        print(\"Dosya içeriği:\", icerik)\n","except FileNotFoundError:\n","    print(\"Hata: Dosya bulunamadı.\")\n","except PermissionError:\n","    print(\"Hata: Dosya erişim izni reddedildi.\")\n","except Exception as err:\n","    print(f\"Beklenmeyen bir hata oluştu: {err}\")\n","else:\n","    print(\"Dosya başarıyla okundu.\")\n","finally:\n","    print(\"Dosya işlemleri tamamlandı.\")"],"metadata":{"id":"2a_zoObSaayT"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["- **try bloğu**: Dosyayı açmaya çalışır. Eğer dosya mevcut değilse ya da başka bir hata oluşursa, ilgili `except` blokları devreye girer.\n","- **except blokları**: Özel hata türlerini yakalar ve kullanıcıya bilgi verir.\n","- **else bloğu**: Eğer hata oluşmazsa çalışır, dosyanın başarıyla okunduğunu bildirir.\n","- **finally bloğu**: Her durumda çalışır ve dosya işlemlerinin tamamlandığını bildirir."],"metadata":{"id":"zy28CHX0abOw"}},{"cell_type":"code","source":["with open(\"yenidosya.txt\", \"x\") as f: # yenidosya.txt eğer yoksa oluşturur var ise hata verir.\n","  f.write(\"Yeni dosya oluşturuldu.\")"],"metadata":{"id":"mtmXm8VobJ2v"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["try:\n","  with open(\"yeni_dosya.txt\", \"x\") as f: # yenidosya.txt eğer yoksa oluşturur var ise hata verir.\n","    f.write(\"Yeni dosya oluşturuldu.\")\n","except FileExistsError:\n","  print(f\"Dizinde {f.name} isimli dosya zaten var.\")"],"metadata":{"id":"9qv9MlZ1YnZs"},"execution_count":null,"outputs":[]}]}